"""Company research, stored: legacy company snapshots, application snapshots,
and their sources.

Originally specified by `specs/008-company-research/plan.md` §5 as two layers;
reshaped by `specs/010-role-aware-research` (migration 0020), which replaced the
never-wired Layer 2 table with the application-scoped snapshot that is now the
primary record. `CompanyResearchSnapshot` remains as the read-only legacy shape
(FR-014). The shape of what follows is an argument rather than a transcription:

**Two tables, one per layer — not one table with a `scope` discriminator.** A
single row carrying both layers would duplicate the company understanding for
every application to that employer and forfeit exactly the reuse that motivates
the split. The two layers also differ in shape, not merely in scope: Layer 1's
sections are **fixed** (a missing one is unrepresentable, which is what makes
"we looked and found nothing" distinguishable from "nobody asked"), while Layer
2's findings are a **variable** list shaped by the role.

**`company_research_snapshots` has no `application_id`, and the absence is the
feature.** FR-021 requires Layer 1 to read identically for two different jobs at
the same employer. Three things enforce it and this is the third: the completion
schema has no field a job could arrive through
(`domain/schemas/research.py`), `research_company()` takes no job argument, and
this table cannot store one. Note that **`spec.md` FR-013 reads "may optionally
reference the application whose context prompted it"** — that sentence predates
the two-layer decision (OQ-F), which moved the application scope to Layer 2
wholesale. `plan.md` §5 is the later document and says "No `application_id`"; it
governs. Reintroducing the column would satisfy the older sentence and break
the newer requirement.

**Immutability is enforced by an absence** (FR-010, FR-011): no `updated_at`,
and no update path in the repository layer. Slice 003's `rejected`-column lesson
says an invariant enforced by an absence has nothing to catch its return, so
`tests/unit/test_research_models.py` asserts each absence and each was watched
failing.

**The migration is `0019_company_research`**, chained from
`0018_corpus_embedding_model`. The models were written first and the migration
autogenerated from them — the ordering slice 006 used for T004 and T005, and for
the same reason: a migration generated from declared models can be *reviewed
against the intent*, while a hand-written one can only be hoped over. That review
earned itself back again here. It stripped eleven out-of-scope `server_default`
alterations against tables holding the paid evaluation data, and it found that
this file promised something it did not enforce — see `ResearchSource`.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime
from decimal import Decimal
from typing import Any

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from careerhq.infrastructure.database import Base


class ResearchStatus(enum.StrEnum):
    """How a research run ended.

    A failed run is a **recorded** run. Slice 005 learned this the expensive way:
    a run that vanishes on failure reports `$0` spent, which reads as free when
    the plan and draft calls had already been billed. `$0.506821` of real spend
    was lost to three such runs before `UsageRecorder` existed.
    """

    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"


class FetchStatus(enum.StrEnum):
    """What happened when CareerHQ tried to read a source.

    **`FAILED` and `REFUSED` are different outcomes and must stay apart.**
    `FAILED` is a network fact — the page did not come back. `REFUSED` is a
    *decision*: the SSRF guard rejected the address (FR-015), or the page
    yielded only template placeholders and was refused as unreadable rather than
    "extracted" into `{{position.name}}` (FR-017). Collapsing them would make a
    security refusal indistinguishable from a timeout in the one record that
    could tell an operator which happened.
    """

    RETRIEVED = "retrieved"
    FAILED = "failed"
    REFUSED = "refused"


def _snapshot_pk() -> Mapped[uuid.UUID]:
    return mapped_column(
        PgUUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )


class CompanyResearchSnapshot(Base):
    """Layer 1 — the general company understanding, reusable across every
    application to that employer.

    Company-scoped and **role-independent** (FR-021). See the module docstring
    for why there is no `application_id` here and why adding one would be a
    requirements regression rather than a convenience.
    """

    __tablename__ = "company_research_snapshots"

    id: Mapped[uuid.UUID] = _snapshot_pk()
    #: Ownership comes from the session, never from the request (FR-018).
    user_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    #: **The reuse axis** (FR-013, US4). `Company` is per-user already, so this
    #: does not widen what one account can see.
    company_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), ForeignKey("companies.id", ondelete="CASCADE"), nullable=False
    )

    #: Displayed prominently (US3), and the input to **both** windows in OQ-E:
    #: reuse at 30 days because it decides spend, staleness at 90 because old
    #: research stays useful when it is honestly labelled.
    retrieved_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    #: The five **fixed** sections of `CompanyResearch`, serialised. Fixed rather
    #: than a list so a missing section is unrepresentable: an empty section
    #: carries its own `empty_reason`, and silence and absence stay distinct.
    sections: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)

    #: Principle V, and slice 007 compares like with like using these.
    model_config_used: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    prompt_version: Mapped[str | None] = mapped_column(String(32), nullable=True)
    input_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    output_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    cost: Mapped[Decimal] = mapped_column(Numeric(12, 6), nullable=False, default=Decimal("0"))

    status: Mapped[str] = mapped_column(String(16), nullable=False, default=ResearchStatus.RUNNING)
    failure_reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    sources: Mapped[list[ResearchSource]] = relationship(
        back_populates="company_snapshot",
        cascade="all, delete-orphan",
        primaryjoin="CompanyResearchSnapshot.id == ResearchSource.company_snapshot_id",
    )

    __table_args__ = (
        CheckConstraint(
            "status IN ('running', 'succeeded', 'failed')",
            name="ck_company_research_snapshots_status",
        ),
        CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0",
            name="ck_company_research_snapshots_tokens_non_negative",
        ),
        CheckConstraint("cost >= 0", name="ck_company_research_snapshots_cost_non_negative"),
        # The reuse lookup: newest successful snapshot for a company.
        Index(
            "ix_company_research_snapshots_company_retrieved",
            "company_id",
            "retrieved_at",
        ),
        # **One run at a time per company, enforced by the database.** Slice 005
        # states the reason exactly: "an application-level check loses to a
        # double-click; a partial unique index does not." A read-then-write guard
        # cannot be made safe here because the two requests are separate
        # transactions.
        #
        # What it prevents is not merely untidy: two concurrent Layer 1 runs both
        # bill a full cold run (~$0.10-0.20 each), both succeed, and
        # `current_research_snapshot_id` ends at whichever finishes last — so the
        # pointer is decided by a race rather than by the user.
        #
        # Partial, because it must constrain only runs in flight: finished
        # snapshots accumulate forever by design (FR-011), and a plain unique
        # index would allow exactly one snapshot per company ever.
        Index(
            "uq_company_research_one_running_per_company",
            "company_id",
            unique=True,
            postgresql_where=text("status = 'running'"),
        ),
    )

    def __repr__(self) -> str:
        return f"<CompanyResearchSnapshot {self.id} company={self.company_id}>"


class ApplicationResearchSnapshot(Base):
    """One research run for one application (slice 010, decision 1A).

    **Reshaped in place from `role_research_snapshots` by migration 0020**,
    which was legitimate only because that table was provably empty — Layer 2
    was never wired to a route. Two deliberate absences carry the design:

    * **No `company_research_snapshot_id`.** The 008 lineage column pointed a
      role brief at the Layer 1 snapshot it rested on. In this design there is
      no Layer 1 underneath — the snapshot *is* the whole research — and a
      permanently-NULL vestige would be the unanswerable kind of column the
      original docstring warned about (research.md D2).
    * **No `updated_at` and no update path.** Immutability by absence, exactly
      as 008 established (Principle IV); `test_application_research_model.py`
      asserts it, because an invariant enforced by an absence has nothing else
      to catch its return.

    `sections` stores **whatever shape the producing path emitted**, unconverted
    — the `app-v1` section shape from the provider, or 008's tiered
    `CompanyResearch` from the builtin fallback — discriminated by
    `prompt_version` (D3). Converting either way would fabricate or discard
    provenance.
    """

    __tablename__ = "application_research_snapshots"

    id: Mapped[uuid.UUID] = _snapshot_pk()
    user_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    application_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), ForeignKey("applications.id", ondelete="CASCADE"), nullable=False
    )

    retrieved_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    #: The producing path's result, unconverted. Shape follows `prompt_version`.
    sections: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)

    #: `provider:tavily-research` or `builtin` — always truthful about which
    #: path made this (FR-005). The API's third value, `legacy-company`, is
    #: derived at read time for 008-era company snapshots and never stored, so
    #: it deliberately does not appear in any constraint here.
    produced_by: Mapped[str] = mapped_column(String(32), nullable=False)

    model_config_used: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    prompt_version: Mapped[str | None] = mapped_column(String(32), nullable=True)
    input_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    output_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    cost: Mapped[Decimal] = mapped_column(Numeric(12, 6), nullable=False, default=Decimal("0"))
    #: `recorded` — exact usage from the seam (fallback path) — or `estimate` —
    #: a documented-rate figure, because the provider's billing is not returned
    #: with the response (D5). Never NULL: a run that cannot say which kind of
    #: number it recorded has not recorded one.
    cost_basis: Mapped[str] = mapped_column(String(16), nullable=False)

    status: Mapped[str] = mapped_column(String(16), nullable=False, default=ResearchStatus.RUNNING)
    failure_reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    sources: Mapped[list[ResearchSource]] = relationship(
        back_populates="application_snapshot",
        cascade="all, delete-orphan",
        primaryjoin=("ApplicationResearchSnapshot.id == ResearchSource.application_snapshot_id"),
    )

    __table_args__ = (
        CheckConstraint(
            "status IN ('running', 'succeeded', 'failed')",
            name="ck_application_research_snapshots_status",
        ),
        CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0",
            name="ck_application_research_snapshots_tokens_non_negative",
        ),
        CheckConstraint("cost >= 0", name="ck_application_research_snapshots_cost_non_negative"),
        CheckConstraint(
            "cost_basis IN ('recorded', 'estimate')",
            name="ck_application_research_snapshots_cost_basis",
        ),
        Index("ix_application_research_snapshots_application", "application_id"),
        # Per application, carried over from 0019's Layer 2 guard: two
        # applications at the same employer may legitimately research at the
        # same time — that independence is the whole of decision 1A.
        Index(
            "uq_application_research_one_running_per_application",
            "application_id",
            unique=True,
            postgresql_where=text("status = 'running'"),
        ),
    )

    def __repr__(self) -> str:
        return f"<ApplicationResearchSnapshot {self.id} application={self.application_id}>"


class ResearchSource(Base):
    """One page CareerHQ attempted to read, and the passage it yielded.

    **A source that could not be retrieved is still a row** (FR-009). An absent
    row cannot be told apart from a source nobody tried, and the difference is
    what a reader needs in order to weigh a thin brief: "three of eight sources
    refused" is a fact about the research, not an implementation detail.

    **`excerpt` is what makes FR-032 possible.** The verbatim check is a
    deterministic string containment test against the document CareerHQ fetched
    itself — free, and it defeats citation laundering before any model-based
    verifier exists. It works only because `SearchHit` carries no page content
    and *we* did the fetching, which is the trust boundary stated in `ports.py`.

    **This is untrusted content and stays structurally distinct from slice 006's
    curated corpus** (coordination item S5). Text here came from the public web
    and may contain instructions addressed to a model; a shared "document" type
    that lost the untrusted marking would be a security regression, not a
    tidy-up. Slice 006 has now shipped its representation, so S5 is decidable for
    the first time — and it has *not* been decided. These stay separate until it
    is.
    """

    __tablename__ = "research_sources"

    id: Mapped[uuid.UUID] = _snapshot_pk()

    #: Exactly one of the two is set, per the check constraint below. Two
    #: nullable columns rather than a polymorphic `snapshot_id` + `snapshot_kind`
    #: pair, so the database can enforce the reference: a discriminator column
    #: cannot carry a foreign key, and an unenforced pointer into one of two
    #: tables is a dangling row waiting to happen.
    company_snapshot_id: Mapped[uuid.UUID | None] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("company_research_snapshots.id", ondelete="CASCADE"),
        nullable=True,
    )
    application_snapshot_id: Mapped[uuid.UUID | None] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("application_research_snapshots.id", ondelete="CASCADE"),
        nullable=True,
    )

    #: The id the model cites, unique within its snapshot. **Assigned by us,
    #: never taken from the page**, so a claim maps back to the exact text it was
    #: drawn from — the same reason every profile line the tailoring draft may
    #: propose against carries `[id: <uuid>]`.
    source_id: Mapped[str] = mapped_column(String(32), nullable=False)

    url: Mapped[str] = mapped_column(String(2048), nullable=False)
    title: Mapped[str | None] = mapped_column(String(512), nullable=True)
    #: Per source, because a run spans time and "when was this true" is asked of
    #: the page, not of the run.
    retrieved_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    #: A representative supporting passage, where a surviving claim cites this
    #: source — **and NULL is a legitimate, expected value.**
    #:
    #: `0019` originally carried
    #: `ck_research_sources_retrieved_has_excerpt`, requiring every `retrieved`
    #: row to hold one. That constraint was wrong and was removed before the
    #: migration shipped: a run reads several pages and the model cites some of
    #: them, so a page that was retrieved and cited by nothing is an ordinary
    #: outcome. The constraint made that row unwritable, which understated how
    #: much of the web was consulted — the opposite of what FR-009 is for.
    #:
    #: **The evidence of record is not here.** Per-claim excerpts live in the
    #: brief's own JSONB (`sections` / `findings`), which is where FR-008 puts
    #: them and what FR-032 verified verbatim at write time. This column holds
    #: *one* passage for display alongside the source; treating it as the
    #: citation record would give slice 007 a second copy to disagree with the
    #: first.
    excerpt: Mapped[str | None] = mapped_column(Text, nullable=True)
    fetch_status: Mapped[str] = mapped_column(String(16), nullable=False)

    company_snapshot: Mapped[CompanyResearchSnapshot | None] = relationship(
        back_populates="sources", foreign_keys=[company_snapshot_id]
    )
    application_snapshot: Mapped[ApplicationResearchSnapshot | None] = relationship(
        back_populates="sources", foreign_keys=[application_snapshot_id]
    )

    __table_args__ = (
        CheckConstraint(
            "fetch_status IN ('retrieved', 'failed', 'refused')",
            name="ck_research_sources_fetch_status",
        ),
        # Exactly one owner. Written as a constraint rather than checked in the
        # repository because an application-level check can be raced or
        # forgotten by the next call site; this cannot.
        CheckConstraint(
            "(company_snapshot_id IS NOT NULL) <> (application_snapshot_id IS NOT NULL)",
            name="ck_research_sources_exactly_one_snapshot",
        ),
        # **`source_id` is unique within its snapshot, and the database is what
        # says so.** The docstring above claims a claim maps back to "the exact
        # text it was drawn from"; without this, two sources in one snapshot
        # could share `s1` and that sentence would be false — a citation would
        # resolve to whichever row came back first, and FR-032's verbatim check
        # would verify an excerpt the claim was never drawn from. This is the
        # same failure slice 005 had when a proposal could not be mapped to a
        # master row, and the same answer: an id that does not identify is worse
        # than no id, because it looks like it works.
        #
        # Partial, and two of them, because ownership is one-of-two: a plain
        # UNIQUE over a nullable column would admit unlimited NULL rows (Postgres
        # treats NULLs as distinct), so the constraint would silently cover only
        # half the table. Each index also serves as the lookup index for its
        # side, which is why the plain ones it replaces are gone.
        Index(
            "uq_research_sources_company_snapshot_source_id",
            "company_snapshot_id",
            "source_id",
            unique=True,
            postgresql_where=text("company_snapshot_id IS NOT NULL"),
        ),
        Index(
            "uq_research_sources_application_snapshot_source_id",
            "application_snapshot_id",
            "source_id",
            unique=True,
            postgresql_where=text("application_snapshot_id IS NOT NULL"),
        ),
    )

    def __repr__(self) -> str:
        return f"<ResearchSource {self.source_id} {self.fetch_status} {self.url!r}>"


__all__ = [
    "ApplicationResearchSnapshot",
    "CompanyResearchSnapshot",
    "FetchStatus",
    "ResearchSource",
    "ResearchStatus",
]
