"""Profile content and resume import staging (T030).

Adds the staging tables an import writes to before approval, and the profile
entities approval writes into. Two constraints here are the point rather than
housekeeping:

* ``uq_resume_profiles_one_master_per_profile`` — a partial unique index making
  it impossible to hold two Master Resumes for one profile. A double-clicked
  approve is the realistic path to that bug, and an application-level check
  could be raced by exactly the double-click it is meant to stop (C4, SC-004).
* ``ck_extraction_confidence`` — confidence stays within 0..1, because a score
  outside it would silently reorder a review queue.

Revision ID: 0003_profile_content
Revises: 0002_users_profiles
Create Date: 2026-08-13 18:06:38.858135
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003_profile_content"
down_revision: str | None = "0002_users_profiles"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "imported_resumes",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("extraction_error", sa.Text(), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("is_fixture", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_imported_resumes_user_id"), "imported_resumes", ["user_id"], unique=False
    )
    op.create_table(
        "certifications",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("issuer", sa.String(length=255), nullable=True),
        sa.Column("year", sa.String(length=32), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["professional_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_certifications_profile_id"), "certifications", ["profile_id"], unique=False
    )
    op.create_table(
        "contact_information",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("links", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["professional_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contact_information_profile_id"),
        "contact_information",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "education",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("institution", sa.String(length=255), nullable=False),
        sa.Column("qualification", sa.String(length=255), nullable=True),
        sa.Column("field_of_study", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.String(length=64), nullable=True),
        sa.Column("end_date", sa.String(length=64), nullable=True),
        sa.Column("grade", sa.String(length=128), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["professional_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_education_profile_id"), "education", ["profile_id"], unique=False)
    op.create_table(
        "extraction_items",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("imported_resume_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), server_default=sa.text("0.5"), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1", name="ck_extraction_confidence"),
        sa.ForeignKeyConstraint(
            ["imported_resume_id"], ["imported_resumes.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["extraction_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_extraction_items_imported_resume_id"),
        "extraction_items",
        ["imported_resume_id"],
        unique=False,
    )
    op.create_table(
        "languages",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("proficiency", sa.String(length=128), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["professional_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_languages_profile_id"), "languages", ["profile_id"], unique=False)
    op.create_table(
        "professional_titles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["professional_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_professional_titles_profile_id"),
        "professional_titles",
        ["profile_id"],
        unique=False,
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["professional_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_profile_id"), "projects", ["profile_id"], unique=False)
    op.create_table(
        "resume_profiles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_master", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["professional_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resume_profiles_profile_id"), "resume_profiles", ["profile_id"], unique=False
    )
    op.create_index(
        "uq_resume_profiles_one_master_per_profile",
        "resume_profiles",
        ["profile_id"],
        unique=True,
        postgresql_where=sa.text("is_master"),
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["professional_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skills_profile_id"), "skills", ["profile_id"], unique=False)
    op.create_table(
        "summary_blocks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["professional_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_summary_blocks_profile_id"), "summary_blocks", ["profile_id"], unique=False
    )
    op.create_table(
        "work_experiences",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("company", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.String(length=64), nullable=True),
        sa.Column("end_date", sa.String(length=64), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["professional_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_work_experiences_profile_id"), "work_experiences", ["profile_id"], unique=False
    )
    op.create_table(
        "experience_bullets",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("experience_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["experience_id"], ["work_experiences.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experience_bullets_experience_id"),
        "experience_bullets",
        ["experience_id"],
        unique=False,
    )
    op.drop_constraint(op.f("uq_users_google_sub"), "users", type_="unique")
    op.drop_index(op.f("ix_users_google_sub"), table_name="users")
    op.create_index(op.f("ix_users_google_sub"), "users", ["google_sub"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_google_sub"), table_name="users")
    op.create_index(op.f("ix_users_google_sub"), "users", ["google_sub"], unique=False)
    op.create_unique_constraint(
        op.f("uq_users_google_sub"), "users", ["google_sub"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_experience_bullets_experience_id"), table_name="experience_bullets")
    op.drop_table("experience_bullets")
    op.drop_index(op.f("ix_work_experiences_profile_id"), table_name="work_experiences")
    op.drop_table("work_experiences")
    op.drop_index(op.f("ix_summary_blocks_profile_id"), table_name="summary_blocks")
    op.drop_table("summary_blocks")
    op.drop_index(op.f("ix_skills_profile_id"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(
        "uq_resume_profiles_one_master_per_profile",
        table_name="resume_profiles",
        postgresql_where=sa.text("is_master"),
    )
    op.drop_index(op.f("ix_resume_profiles_profile_id"), table_name="resume_profiles")
    op.drop_table("resume_profiles")
    op.drop_index(op.f("ix_projects_profile_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_professional_titles_profile_id"), table_name="professional_titles")
    op.drop_table("professional_titles")
    op.drop_index(op.f("ix_languages_profile_id"), table_name="languages")
    op.drop_table("languages")
    op.drop_index(op.f("ix_extraction_items_imported_resume_id"), table_name="extraction_items")
    op.drop_table("extraction_items")
    op.drop_index(op.f("ix_education_profile_id"), table_name="education")
    op.drop_table("education")
    op.drop_index(op.f("ix_contact_information_profile_id"), table_name="contact_information")
    op.drop_table("contact_information")
    op.drop_index(op.f("ix_certifications_profile_id"), table_name="certifications")
    op.drop_table("certifications")
    op.drop_index(op.f("ix_imported_resumes_user_id"), table_name="imported_resumes")
    op.drop_table("imported_resumes")
    # ### end Alembic commands ###
