"""Military service and volunteer experience.

docs/03 §4.2 lists both as owned information; the extraction schema had neither,
so a real CV's "Military Service - Israeli Navy / Electrician" was filed as
employment at 0.30 confidence. The model had nowhere better to put it, and the
profile would have asserted something untrue.

Revision ID: 0004_service_volunteering
Revises: 0003_profile_content
Create Date: 2026-08-13 19:09:36.545778
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004_service_volunteering"
down_revision: str | None = "0003_profile_content"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "military_service",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("branch", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.String(length=64), nullable=True),
        sa.Column("end_date", sa.String(length=64), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["professional_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_military_service_profile_id"), "military_service", ["profile_id"], unique=False
    )
    op.create_table(
        "volunteer_experiences",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("organisation", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.String(length=64), nullable=True),
        sa.Column("end_date", sa.String(length=64), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["professional_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_volunteer_experiences_profile_id"),
        "volunteer_experiences",
        ["profile_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_volunteer_experiences_profile_id"), table_name="volunteer_experiences")
    op.drop_table("volunteer_experiences")
    op.drop_index(op.f("ix_military_service_profile_id"), table_name="military_service")
    op.drop_table("military_service")
    # ### end Alembic commands ###
