"""Company research: two snapshot layers, their sources, and the current pointer.

Slice 008, `plan.md` §5 and §8 step 1. Chains from `0018_corpus_embedding_model`,
which is slice 006's final head and what production runs — **rebased, never
branched**. Slice 007 was checked before this was written and adds no migration
of its own, so the head collision that coordination item S6 anticipated did not
materialise.

**Autogenerated, then reviewed against the intent rather than accepted.** That
review is the reason this file is trustworthy, and it changed three things:

1. **Eleven out-of-scope `server_default=None` alterations were stripped** —
   against `applications`, `match_analyses`, `resume_version_items`,
   `resume_versions`, `reviewer_findings` and `tailoring_runs`. This is
   **pre-existing model/database drift**, not slice 008's: those models declare a
   Python-side `default=` while the database carries a `server_default`, so
   autogenerate proposes removing the database's. Slice 006's `0015` was offered
   the identical eleven and stripped them for the identical reason. Applying them
   would silently alter six tables holding the paid evaluation evidence in a
   migration whose subject is company research. **The drift is still there and is
   still nobody's task.**
2. **Two partial unique indexes were added**, after the review found the model
   claimed something the schema did not enforce — see below.
3. Nothing else. The three tables, the pointer column, the circular foreign key
   and every check constraint came from autogenerate unmodified.

**The circular foreign key.** `companies.current_research_snapshot_id` points at
`company_research_snapshots`, which points back at `companies`. The constraint is
therefore created by a **separate `ALTER TABLE`** after both tables exist, and it
is **named** — an unnamed `use_alter` constraint cannot be dropped, which would
leave this migration with no working downgrade.

**`source_id` is unique within its snapshot, and two partial indexes say so.**
Autogenerate could not have found this: it faithfully reproduced a model that was
missing the constraint. The model promised a claim maps back to the exact text it
was drawn from; without uniqueness two sources in one snapshot could share `s1`,
a citation would resolve to whichever row came back first, and FR-032's verbatim
check would compare an excerpt against a page the claim never came from. Partial
rather than plain because ownership is one-of-two and Postgres treats NULLs as
distinct — a plain UNIQUE over a nullable column admits unlimited NULL rows and
would have covered only half the table while looking complete.

**What autogenerate cannot see at all**: check-constraint changes. Alembic does
not diff them. Every `CheckConstraint` here is therefore load-bearing on first
write and was proved against a real database by
`tests/integration/test_research_persistence.py`, not by its declaration.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0019_company_research"
down_revision: str | None = "0018_corpus_embedding_model"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_research_snapshots",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column(
            "retrieved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_config_used", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed')",
            name="ck_company_research_snapshots_status",
        ),
        sa.CheckConstraint("cost >= 0", name="ck_company_research_snapshots_cost_non_negative"),
        sa.CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0",
            name="ck_company_research_snapshots_tokens_non_negative",
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_company_research_snapshots_company_retrieved",
        "company_research_snapshots",
        ["company_id", "retrieved_at"],
        unique=False,
    )
    # One in-flight Layer 1 run per company. Partial, so finished snapshots
    # still accumulate without limit (FR-011); a plain unique index would allow
    # exactly one snapshot per company ever.
    op.create_index(
        "uq_company_research_one_running_per_company",
        "company_research_snapshots",
        ["company_id"],
        unique=True,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_table(
        "role_research_snapshots",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("company_research_snapshot_id", sa.UUID(), nullable=False),
        sa.Column(
            "retrieved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("findings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_config_used", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed')", name="ck_role_research_snapshots_status"
        ),
        sa.CheckConstraint("cost >= 0", name="ck_role_research_snapshots_cost_non_negative"),
        sa.CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0",
            name="ck_role_research_snapshots_tokens_non_negative",
        ),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["company_research_snapshot_id"], ["company_research_snapshots.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_role_research_snapshots_application",
        "role_research_snapshots",
        ["application_id"],
        unique=False,
    )
    # The Layer 2 counterpart, scoped to the application: two applications at
    # the same employer may research their own roles concurrently.
    op.create_index(
        "uq_role_research_one_running_per_application",
        "role_research_snapshots",
        ["application_id"],
        unique=True,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_table(
        "research_sources",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("company_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("role_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("source_id", sa.String(length=32), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column(
            "retrieved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.Column("fetch_status", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "fetch_status IN ('retrieved', 'failed', 'refused')",
            name="ck_research_sources_fetch_status",
        ),
        sa.CheckConstraint(
            "(company_snapshot_id IS NOT NULL) <> (role_snapshot_id IS NOT NULL)",
            name="ck_research_sources_exactly_one_snapshot",
        ),
        sa.ForeignKeyConstraint(
            ["company_snapshot_id"], ["company_research_snapshots.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["role_snapshot_id"], ["role_research_snapshots.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_research_sources_company_snapshot_source_id",
        "research_sources",
        ["company_snapshot_id", "source_id"],
        unique=True,
        postgresql_where=sa.text("company_snapshot_id IS NOT NULL"),
    )
    op.create_index(
        "uq_research_sources_role_snapshot_source_id",
        "research_sources",
        ["role_snapshot_id", "source_id"],
        unique=True,
        postgresql_where=sa.text("role_snapshot_id IS NOT NULL"),
    )
    op.add_column("companies", sa.Column("current_research_snapshot_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_companies_current_research_snapshot",
        "companies",
        "company_research_snapshots",
        ["current_research_snapshot_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_companies_current_research_snapshot", "companies", type_="foreignkey")
    op.drop_column("companies", "current_research_snapshot_id")
    op.drop_index(
        "uq_research_sources_role_snapshot_source_id",
        table_name="research_sources",
        postgresql_where=sa.text("role_snapshot_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_research_sources_company_snapshot_source_id",
        table_name="research_sources",
        postgresql_where=sa.text("company_snapshot_id IS NOT NULL"),
    )
    op.drop_table("research_sources")
    op.drop_index(
        "uq_role_research_one_running_per_application",
        table_name="role_research_snapshots",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_index("ix_role_research_snapshots_application", table_name="role_research_snapshots")
    op.drop_table("role_research_snapshots")
    op.drop_index(
        "uq_company_research_one_running_per_company",
        table_name="company_research_snapshots",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_index(
        "ix_company_research_snapshots_company_retrieved", table_name="company_research_snapshots"
    )
    op.drop_table("company_research_snapshots")
    # ### end Alembic commands ###
