"""Generate the sample CV fixtures used by the extraction tests.

The fixtures are committed, but this script is committed with them so they are
reproducible and inspectable rather than opaque binaries someone is afraid to
touch. Re-run it from `backend/`:

    .venv/bin/python tests/fixtures/make_fixtures.py

The person is fictional. Extraction tests must never depend on a real CV: it
would put personal data in the repository and make the test unreproducible for
anyone else.
"""

from __future__ import annotations

import pathlib

HERE = pathlib.Path(__file__).parent

# A deliberately ordinary single-column CV — the shape SC-002's 80% target is
# measured against. Two roles with distinct bullets, because bullet-to-role
# attribution is the thing most likely to go wrong.
LINES = [
    "ALEX MORGAN",
    "Senior Backend Engineer",
    "alex.morgan@example.com | +44 7700 900123 | London, UK",
    "linkedin.com/in/alexmorgan-example",
    "",
    "SUMMARY",
    "Backend engineer with eight years building distributed systems in Python and Go.",
    "Focused on payments infrastructure and the reliability of systems that move money.",
    "",
    "EXPERIENCE",
    "",
    "Staff Engineer, Northwind Payments",
    "March 2021 - Present, London",
    "- Led the migration of the ledger service from a monolith to seven services,",
    "  cutting p99 settlement latency from 1.8s to 240ms.",
    "- Designed the idempotency layer that made retried payment requests safe,",
    "  eliminating a class of double-charge incidents.",
    "- Mentored four engineers, two of whom were promoted within the year.",
    "",
    "Senior Software Engineer, Calder Logistics",
    "June 2018 - February 2021, Manchester",
    "- Built the route optimisation service handling 40,000 daily shipments.",
    "- Reduced cloud spend 34% by rewriting the batch pipeline in Go.",
    "",
    "SKILLS",
    "Python, Go, PostgreSQL, Kafka, Kubernetes, Terraform, gRPC, Redis",
    "",
    "EDUCATION",
    "BSc Computer Science, University of Manchester, 2014 - 2017, First Class Honours",
    "",
    "CERTIFICATIONS",
    "Certified Kubernetes Administrator, Cloud Native Computing Foundation, 2022",
    "",
    "LANGUAGES",
    "English (native), Spanish (professional working proficiency)",
]


def write_pdf(path: pathlib.Path) -> None:
    """Write a minimal single-page PDF with a real text layer.

    Handwritten rather than generated by a library: the only thing needed is a
    text layer pdfplumber can read, and adding a PDF-writing dependency to ship
    two fixtures is a poor trade. The xref offsets are computed rather than
    guessed, because a wrong offset produces a file that opens in some readers
    and fails in others — the worst possible fixture.
    """
    content = ["BT", "/F1 10 Tf", "12 TL", "1 0 0 1 40 760 Tm"]
    for line in LINES:
        escaped = line.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")
        content.append(f"({escaped}) Tj")
        content.append("T*")
    content.append("ET")
    stream = "\n".join(content).encode("latin-1")

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
        b"/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
        b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>",
    ]

    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for i, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{i} 0 obj\n".encode() + body + b"\nendobj\n"

    xref_at = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode()
    out += b"0000000000 65535 f \n"
    for off in offsets:
        out += f"{off:010d} 00000 n \n".encode()
    out += (
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_at}\n%%EOF\n"
    ).encode()

    path.write_bytes(bytes(out))


def write_docx(path: pathlib.Path) -> None:
    from docx import Document

    doc = Document()
    for line in LINES:
        doc.add_paragraph(line)
    doc.save(path)


def write_scanned_pdf(path: pathlib.Path) -> None:
    """A PDF with no text layer at all.

    The fixture for FR-008: extraction must report failure rather than present
    an empty review form implying the CV was understood and found to be empty.
    A single filled rectangle stands in for a scan — what matters is that there
    is nothing to extract.
    """
    stream = b"0.9 0.9 0.9 rg\n40 40 515 762 re\nf\n"
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << >> >>",
        b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream",
    ]
    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for i, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{i} 0 obj\n".encode() + body + b"\nendobj\n"
    xref_at = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode()
    out += b"0000000000 65535 f \n"
    for off in offsets:
        out += f"{off:010d} 00000 n \n".encode()
    out += (
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_at}\n%%EOF\n"
    ).encode()
    path.write_bytes(bytes(out))


if __name__ == "__main__":
    write_pdf(HERE / "sample_cv.pdf")
    write_docx(HERE / "sample_cv.docx")
    write_scanned_pdf(HERE / "scanned_no_text.pdf")
    print("wrote sample_cv.pdf, sample_cv.docx, scanned_no_text.pdf")
